ci: add automatic guix build

diff --git a/.github/workflows/guix-build.yml b/.github/workflows/guix-build.yml
--- a/.github/workflows/guix-build.yml
+++ b/.github/workflows/guix-build.yml
@@ -8,20 +8,36 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
+      - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Install Dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y git make bash curl bzip2 ca-certificates guix
-          sudo locale-gen en_US.UTF-8
-        shell: bash
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
 
-      - name: Run Guix Build
+      - name: Cache Docker layers
+        uses: actions/cache@v2
+        with:
+          path: /tmp/.buildx-cache
+          key: ${{ runner.os }}-buildx-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-buildx-
+
+      - name: Build Docker image
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          file: ./contrib/guix/Dockerfile
+          load: true
+          cache-from: type=local,src=/tmp/.buildx-cache
+          cache-to: type=local,dest=/tmp/.buildx-cache
+
+      - name: Run Guix build
         run: |
-          ls /
-          ls
-          cd contrib/guix
-          ./guix-build
-        shell: bash
+          docker run --rm -v $(pwd):/dash -w /dash dashpay/dash contrib/guix/guix-build
+
+      - name: Ensure build passes
+        run: |
+          if [[ $? != 0 ]]; then
+            echo "Guix build failed!"
+            exit 1
+          fi
